title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 个人项目
    icon: fas fa-code
    sites:
      - name: 个人博客
        icon: fas fa-blog
        description: 博客展示页面
        url: "https://blog.shogun.xin"
      - name: 管理博客
        icon: fas fa-edit
        description: 管理博客页面
        url: "https://admin.shogun.xin"
      - name: 雷池waf
        icon: fas fa-user-secret
        description: blog防护
        url: "https://safeline.shogun.xin"
